apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cpu-usage-alert-rule
  namespace: monitoring
  labels:
    app: kube-prometheus-stack
    release: prometheus
spec:
  groups:
  - name: pod-cpu-usage
    rules:
    - alert: HighCpuUsage
      expr: sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate) by (namespace)/2*100 > 50
      for: 0m
      labels:
        severity: critical
        namespace: monitoring
      annotations:
        summary: "High CPU usage detected for namespace {{$labels.namespace}}"
        description: "CPU usage for namespace {{ $labels.namespace }} is higher than 50% "
