apiVersion: v1
kind: Secret
metadata:
  name: slack-secret
  namespace: monitoring
data:
  webhook: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDA4MzM5TjIxTVkvQjA4NERRSjZZOEwvcnRrVnFJUWtKM25EYXBrbng3ZGU0Y0lzCg==

