name: cicd workflow
on:
    push:
        branches:
            - main
jobs:
    CICD:
     name: CICD
     runs-on: ubuntu-latest
     steps:
         - name: Checkout
           uses: actions/checkout@v2    
         - name: build the app
           run: mvn clean deploy -Dmaven.test.skip=true
         - name: test the app
           run: mvn surefire-report:report
        

         - name: Set up Docker Buildx
           uses: docker/setup-buildx-action@v2


         - name: Login to Docker Hub
           uses: docker/login-action@v2
           with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}
         - name: ls
           run: ls
         - name: ls the jar
           run: ls jarstaging/com/valaxy/demo-workshop/2.1.2/
         - name: Push to Docker Hub
           uses: docker/build-push-action@v4
           with:
                push: true
                tags: mosama25/java-app:latest

