name: cicd workflow
on:
    push:
        branches:
            - main
jobs:
    CICD:
     name: CICD
     runs-on: ubuntu-latest
     steps:
         - name: Checkout
           uses: actions/checkout@v2    
         - name: build the app
           run: mvn clean deploy -Dmaven.test.skip=true
         - name: test the app
           run: mvn surefire-report:report
        
         - name: build image
           run: docker build . -t mosama25/java-app:v$GITHUB_RUN_NUMBER.0

      # SonarCloud Analysis
         - name: Run SonarCloud Scan
           uses: SonarSource/sonarcloud-github-action@v2
           with:
             args: >
              -Dsonar.projectKey=devops-project-2
              -Dsonar.organization=DevOps-Project-2
           env:
              SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


