name: cicd workflow
on:
    push:
        branches:
            - main
jobs:
    CICD:
     name: CICD
     runs-on: ubuntu-latest
     container:
      image: maven:3.8.8-openjdk-11 # Official Maven + JDK 11 image
     steps:
         - name: Checkout
           uses: actions/checkout@v2    
         - name: build the app
           run: mvn clean deploy -Dmaven.test.skip=true
         - name: test the app
           run: mvn surefire-report:report
      
        #  - name: Install Node.js
        #    uses: actions/setup-node@v3
        #    with:
        #      node-version: '16'
        #  - name: build image
        #    run: docker build . -t mosama25/java-app:v$GITHUB_RUN_NUMBER.0

         - name: Run SonarCloud Scan
           uses: sonarsource/sonarqube-scan-action@master
           env:
             SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
             SONAR_HOST_URL: "http://44.212.36.135"


