name: CICD workflow
on:
    push:
        branches:
            - main
jobs:
    CICD:
     name: CICD
     runs-on: ubuntu-latest
     steps:
         - name: Checkout
           uses: actions/checkout@v2    
         - name: build the app
           run: mvn clean deploy -Dmaven.test.skip=true
         - name: test the app
           run: mvn surefire-report:report
        

         - name: Set up Docker Buildx
           uses: docker/setup-buildx-action@v2


         - name: Login to Docker Hub
           uses: docker/login-action@v2
           with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}
         - name: build image
           run: docker build . -t mosama25/java-app:$GITHUB_RUN_NUMBER
         - name: push image
           run: docker push mosama25/java-app:$GITHUB_RUN_NUMBER

