name: cicd workflow
on:
    push:
        branches:
            - main
jobs:
    CICD:
     name: CICD
     runs-on: ubuntu-latest
     steps:
         - name: Checkout
           uses: actions/checkout@v2    
         - name: build the app
           run: mvn clean deploy -Dmaven.test.skip=true
         - name: test the app
           run: mvn surefire-report:report
      
         - name: Install SonarScanner
           run: |
             wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
             unzip sonar-scanner-cli-4.8.0.2856-linux.zip
             sudo mv sonar-scanner-4.8.0.2856-linux /opt/sonar-scanner
             echo "PATH=$PATH:/opt/sonar-scanner/bin" >> $GITHUB_ENV

         - name: Run SonarCloud Scan
           run : sonar-scanner


