name: cicd workflow
on:
    push:
        branches:
            - main
jobs:
    CICD:
     name: CICD
     runs-on: ubuntu-latest
     steps:
         - name: Checkout
           uses: actions/checkout@v2    
         - name: build the app
           run: mvn clean deploy -Dmaven.test.skip=true
         - name: test the app
           run: mvn surefire-report:report
      
         - name: Install SonarScanner
           run: |
             wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
             unzip sonar-scanner-cli-4.8.0.2856-linux.zip
             sudo mv sonar-scanner-4.8.0.2856-linux /opt/sonar-scanner
             echo "PATH=$PATH:/opt/sonar-scanner/bin" >> $GITHUB_ENV

         - name: Run SonarCloud Scan
           env:
              SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
           run : sonar-scanner -Dsonar.login=$SONAR_TOKEN
               # Check the Quality Gate status.
         - name: SonarQube Quality Gate check
           id: sonarqube-quality-gate-check
           uses: sonarsource/sonarqube-quality-gate-action@master
           with:
             pollingTimeoutSec: 600
           env:
             SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
             SONAR_HOST_URL: http://44.212.36.135 #OPTIONAL


